# Generated by Django 6.0.4 on 2026-04-07 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Формат мероприятия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('default_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Бюджет по умолчанию')),
            ],
            options={
                'verbose_name': 'Формат мероприятия',
                'verbose_name_plural': 'Форматы мероприятий',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Этап')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('probability', models.PositiveSmallIntegerField(default=0, verbose_name='Вероятность (%)')),
                ('is_lost', models.BooleanField(default=False, verbose_name='Потерянный этап')),
            ],
            options={
                'verbose_name': 'Этап воронки',
                'verbose_name_plural': 'Этапы воронки',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='deal',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company',
        ),
        migrations.RemoveField(
            model_name='client',
            name='notes',
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('b2b', 'B2B'), ('b2c', 'B2C')], default='b2c', max_length=10, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='client',
            name='contacts',
            field=models.TextField(blank=True, verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='client',
            name='event_history',
            field=models.TextField(blank=True, verbose_name='История мероприятий'),
        ),
        migrations.AddField(
            model_name='client',
            name='ltv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='LTV'),
        ),
        migrations.AddField(
            model_name='client',
            name='messenger',
            field=models.CharField(blank=True, max_length=100, verbose_name='Мессенджер'),
        ),
        migrations.AddField(
            model_name='client',
            name='preferences',
            field=models.TextField(blank=True, verbose_name='Предпочтения'),
        ),
        migrations.AddField(
            model_name='client',
            name='segment',
            field=models.CharField(choices=[('vip', 'VIP'), ('standard', 'Стандарт')], default='standard', max_length=20, verbose_name='Сегмент'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя / компания'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название мероприятия')),
                ('date', models.DateField(verbose_name='Дата')),
                ('city', models.CharField(max_length=120, verbose_name='Город')),
                ('guests_count', models.PositiveIntegerField(default=0, verbose_name='Количество гостей')),
                ('planned_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Бюджет плановый')),
                ('goal', models.TextField(blank=True, verbose_name='Цель мероприятия')),
                ('preferences', models.TextField(blank=True, verbose_name='Предпочтения')),
                ('stop_factors', models.TextField(blank=True, verbose_name='Стоп-факторы')),
                ('status', models.CharField(choices=[('planning', 'Планирование'), ('in_progress', 'В реализации'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='planning', max_length=20, verbose_name='Статус реализации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.client', verbose_name='Клиент')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_events', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager')),
                ('event_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.eventformat', verbose_name='Формат')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ('date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='EventCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('call', 'Звонок'), ('message', 'Сообщение'), ('meeting', 'Встреча')], max_length=20, verbose_name='Тип')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='core.event', verbose_name='Мероприятие')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_communications', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Коммуникация',
                'verbose_name_plural': 'Коммуникации',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract', 'Договор'), ('invoice', 'Счёт'), ('proposal', 'КП'), ('act', 'Акт')], max_length=20, verbose_name='Тип')),
                ('file', models.FileField(blank=True, upload_to='event_documents/', verbose_name='Файл')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('signed', 'Подписан')], default='draft', max_length=20, verbose_name='Статус')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='EventExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120, verbose_name='Категория')),
                ('vendor_name', models.CharField(blank=True, max_length=255, verbose_name='Подрядчик')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('prepayment', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Предоплата')),
                ('payment_status', models.CharField(choices=[('planned', 'Запланировано'), ('partial', 'Частично оплачено'), ('paid', 'Оплачено')], default='planned', max_length=20, verbose_name='Статус оплаты')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'ordering': ('category', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EventFormatBudgetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120, verbose_name='Категория')),
                ('vendor_name', models.CharField(blank=True, max_length=255, verbose_name='Подрядчик')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('event_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_templates', to='core.eventformat', verbose_name='Формат мероприятия')),
            ],
            options={
                'verbose_name': 'Шаблон бюджета',
                'verbose_name_plural': 'Шаблоны бюджета',
            },
        ),
        migrations.CreateModel(
            name='EventFormatTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Задача')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('deadline_offset_days', models.IntegerField(default=0, verbose_name='Смещение дедлайна')),
                ('event_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='core.eventformat', verbose_name='Формат мероприятия')),
            ],
            options={
                'verbose_name': 'Шаблон задачи',
                'verbose_name_plural': 'Шаблоны задач',
            },
        ),
        migrations.CreateModel(
            name='EventFormatTimelineTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время')),
                ('block', models.CharField(max_length=120, verbose_name='Блок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('responsible_label', models.CharField(blank=True, max_length=120, verbose_name='Ответственный')),
                ('event_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_templates', to='core.eventformat', verbose_name='Формат мероприятия')),
            ],
            options={
                'verbose_name': 'Шаблон тайминга',
                'verbose_name_plural': 'Шаблоны тайминга',
                'ordering': ('time', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EventOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_feedback', models.TextField(blank=True, verbose_name='Отзыв клиента')),
                ('final_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Финальная прибыль')),
                ('lessons_learned', models.TextField(blank=True, verbose_name='Проблемы / выводы')),
                ('media_links', models.TextField(blank=True, verbose_name='Фото / видео материалы')),
                ('project_rating', models.PositiveSmallIntegerField(default=0, verbose_name='Оценка проекта')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='core.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Итоги мероприятия',
                'verbose_name_plural': 'Итоги мероприятий',
            },
        ),
        migrations.CreateModel(
            name='EventRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание риска')),
                ('probability', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], default='medium', max_length=10, verbose_name='Вероятность')),
                ('plan_b', models.TextField(blank=True, verbose_name='План B')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='core.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Риск',
                'verbose_name_plural': 'Риски',
            },
        ),
        migrations.CreateModel(
            name='EventTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн')),
                ('deadline_offset_days', models.IntegerField(default=0, verbose_name='Смещение дедлайна')),
                ('status', models.CharField(choices=[('todo', 'К выполнению'), ('in_progress', 'В работе'), ('done', 'Готово')], default='todo', max_length=20, verbose_name='Статус')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.event', verbose_name='Мероприятие')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Задача мероприятия',
                'verbose_name_plural': 'Задачи мероприятия',
                'ordering': ('deadline', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EventTimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время')),
                ('block', models.CharField(max_length=120, verbose_name='Блок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('responsible', models.CharField(blank=True, max_length=120, verbose_name='Ответственный')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_items', to='core.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Тайминг',
                'verbose_name_plural': 'Тайминг',
                'ordering': ('time', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('messenger', models.CharField(blank=True, max_length=100, verbose_name='Мессенджер')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('source', models.CharField(blank=True, max_length=120, verbose_name='Источник')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('probability', models.PositiveSmallIntegerField(default=0, verbose_name='Вероятность сделки (%)')),
                ('loss_reason', models.TextField(blank=True, verbose_name='Причина отказа')),
                ('last_contact_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний контакт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер')),
                ('preliminary_event_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.eventformat', verbose_name='Предварительный формат мероприятия')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.pipelinestage', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='event',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.lead', verbose_name='Лид'),
        ),
        migrations.AddField(
            model_name='client',
            name='lead',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='core.lead', verbose_name='Исходный лид'),
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название пакета')),
                ('services', models.TextField(verbose_name='Список услуг')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('event_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='core.eventformat', verbose_name='Формат мероприятия')),
            ],
            options={
                'verbose_name': 'Пакет услуг',
                'verbose_name_plural': 'Пакеты услуг',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TeamMemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('sales_manager', 'Sales Manager'), ('project_manager', 'Project Manager'), ('admin', 'Admin'), ('finance', 'Finance')], max_length=30, verbose_name='Роль')),
                ('can_view_finance', models.BooleanField(default=False, verbose_name='Доступ к финансам')),
                ('can_view_clients', models.BooleanField(default=True, verbose_name='Доступ к клиентам')),
                ('can_view_analytics', models.BooleanField(default=False, verbose_name='Доступ к аналитике')),
                ('can_manage_system', models.BooleanField(default=False, verbose_name='Управление системой')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль сотрудника',
                'verbose_name_plural': 'Профили сотрудников',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя / компания')),
                ('roles', models.CharField(help_text='Например: ведущий, фотограф', max_length=255, verbose_name='Роли')),
                ('min_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Минимальная стоимость')),
                ('avg_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Средняя стоимость')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Рейтинг')),
                ('reliability', models.PositiveSmallIntegerField(default=0, verbose_name='Надёжность (%)')),
                ('contacts', models.TextField(blank=True, verbose_name='Контакты')),
                ('availability_notes', models.TextField(blank=True, verbose_name='Календарь занятости')),
                ('blacklisted', models.BooleanField(default=False, verbose_name='Чёрный список')),
                ('event_formats', models.ManyToManyField(blank=True, related_name='vendors', to='core.eventformat', verbose_name='Форматы мероприятий')),
            ],
            options={
                'verbose_name': 'Подрядчик',
                'verbose_name_plural': 'Подрядчики',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EventVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=120, verbose_name='Роль')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость')),
                ('status', models.CharField(choices=[('proposed', 'Предложен'), ('approved', 'Утверждён'), ('replaced', 'Заменён')], default='proposed', max_length=20, verbose_name='Статус')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_vendors', to='core.event', verbose_name='Мероприятие')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assignments', to='core.vendor', verbose_name='Подрядчик')),
            ],
            options={
                'verbose_name': 'Подрядчик мероприятия',
                'verbose_name_plural': 'Подрядчики мероприятия',
                'unique_together': {('event', 'vendor', 'role')},
            },
        ),
        migrations.CreateModel(
            name='EventFormatVendorTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=120, verbose_name='Роль')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость')),
                ('event_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_templates', to='core.eventformat', verbose_name='Формат мероприятия')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='format_templates', to='core.vendor', verbose_name='Подрядчик')),
            ],
            options={
                'verbose_name': 'Шаблон подрядчика',
                'verbose_name_plural': 'Шаблоны подрядчиков',
            },
        ),
        migrations.DeleteModel(
            name='Deal',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
