# Generated by Django 6.0.4 on 2026-08-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_pipeline_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammemberprofile',
            name='can_manage_clients',
            field=models.BooleanField(default=True, verbose_name='Управление клиентами'),
        ),
        migrations.AddField(
            model_name='teammemberprofile',
            name='can_manage_events',
            field=models.BooleanField(default=True, verbose_name='Управление мероприятиями'),
        ),
        migrations.AddField(
            model_name='teammemberprofile',
            name='can_manage_leads',
            field=models.BooleanField(default=True, verbose_name='Управление лидами'),
        ),
    ]
