# Generated by Django 6.0.4 on 2026-08-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_teammemberprofile_can_manage_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammemberprofile',
            name='can_manage_clients',
            field=models.BooleanField(default=True, help_text='Разрешает создавать и редактировать клиентов. Также нужен доступ к клиентам.', verbose_name='Управление клиентами'),
        ),
        migrations.AlterField(
            model_name='teammemberprofile',
            name='can_manage_events',
            field=models.BooleanField(default=True, help_text='Разрешает создавать и редактировать мероприятия и связанные рабочие данные.', verbose_name='Управление мероприятиями'),
        ),
        migrations.AlterField(
            model_name='teammemberprofile',
            name='can_manage_leads',
            field=models.BooleanField(default=True, help_text='Разрешает создавать и редактировать лидов.', verbose_name='Управление лидами'),
        ),
        migrations.AlterField(
            model_name='teammemberprofile',
            name='can_manage_system',
            field=models.BooleanField(default=False, help_text='Разрешает управлять пользователями и справочниками, а также удалять основные записи.', verbose_name='Управление системой'),
        ),
        migrations.AlterField(
            model_name='teammemberprofile',
            name='can_view_analytics',
            field=models.BooleanField(default=False, help_text='Разрешает открывать страницу аналитики и просматривать графики.', verbose_name='Доступ к аналитике'),
        ),
        migrations.AlterField(
            model_name='teammemberprofile',
            name='can_view_clients',
            field=models.BooleanField(default=True, help_text='Разрешает просмотр раздела клиентов, поиск и фильтрацию.', verbose_name='Доступ к клиентам'),
        ),
        migrations.AlterField(
            model_name='teammemberprofile',
            name='can_view_finance',
            field=models.BooleanField(default=False, help_text='Показывает бюджеты, расходы, прибыль, маржу и финансовую аналитику.', verbose_name='Доступ к финансам'),
        ),
    ]
