# Generated by Django 6.0.4 on 2026-08-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_teammemberprofile_can_manage_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammemberprofile',
            name='can_manage_system',
            field=models.BooleanField(default=False, help_text='Разрешает управлять пользователями, базовыми списками и шаблонами CRM, а также удалять основные записи.', verbose_name='Управление системой'),
        ),
    ]
