# Generated by Django 6.0.4 on 2026-09-13 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_teammemberprofile_can_manage_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoutcome',
            name='project_rating',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка проекта'),
        ),
    ]
