# Generated by Django 6.0.4 on 2026-09-13 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_eventoutcome_project_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventexpense',
            name='vendor_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.eventvendor', verbose_name='Назначенный подрядчик'),
        ),
    ]
