# Generated by Django 6.0.4 on 2026-09-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_eventexpense_vendor_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoutcome',
            name='final_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Финальная прибыль'),
        ),
    ]
