# Generated by Django 6.0.4 on 2026-09-17 20:10

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_eventoutcome_final_profit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventexpense',
            old_name='prepayment',
            new_name='paid_amount',
        ),
        migrations.AlterField(
            model_name='eventexpense',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Оплачено'),
        ),
    ]
