# Generated by Django 6.0.4 on 2026-09-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_expensecategory_eventexpense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Роль подрядчика',
                'verbose_name_plural': 'Роли подрядчиков',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.AlterField(
            model_name='vendor',
            name='roles',
            field=models.CharField(blank=True, help_text='Сохраняется для совместимости со старыми записями', max_length=255, verbose_name='Старые роли'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='role_categories',
            field=models.ManyToManyField(blank=True, related_name='vendors', to='core.vendorrole', verbose_name='Роли и специализации'),
        ),
    ]
