# Generated by Django 6.0.4 on 2026-09-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_vendor_instagram_vendor_vk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='messenger',
        ),
        migrations.AddField(
            model_name='lead',
            name='instagram',
            field=models.CharField(blank=True, help_text='Username или полная ссылка', max_length=150, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='lead',
            name='max_messenger',
            field=models.CharField(blank=True, help_text='Контакт или полная ссылка', max_length=150, verbose_name='MAX'),
        ),
        migrations.AddField(
            model_name='lead',
            name='telegram',
            field=models.CharField(blank=True, help_text='Username или полная ссылка', max_length=150, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='lead',
            name='vk',
            field=models.CharField(blank=True, help_text='Username или полная ссылка', max_length=150, verbose_name='ВКонтакте'),
        ),
        migrations.AddField(
            model_name='lead',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Номер телефона или полная ссылка', max_length=150, verbose_name='WhatsApp'),
        ),
    ]
