# Generated by Django 6.0.4 on 2026-09-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_lead_messenger_lead_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='facebook',
            field=models.CharField(blank=True, help_text='Username или полная ссылка', max_length=150, verbose_name='Facebook'),
        ),
    ]
