# Generated by Django 6.0.4 on 2026-09-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_lead_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='facebook',
            field=models.CharField(blank=True, help_text='Username или полная ссылка', max_length=150, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='preferred_contact_method',
            field=models.CharField(blank=True, choices=[('phone', 'Телефон'), ('email', 'Email'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('max', 'MAX'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('vk', 'ВКонтакте'), ('other', 'Другой')], max_length=20, verbose_name='Предпочтительный способ связи'),
        ),
    ]
