from django.urls import path

from .views import (
    AnalyticsView,
    CalendarView,
    ClientCreateView,
    ClientDeleteView,
    ClientUpdateView,
    ClientListView,
    DashboardView,
    EventCreateView,
    EventDeleteView,
    EventFormatListView,
    EventFormatCreateView,
    EventFormatDeleteView,
    EventFormatUpdateView,
    EventListView,
    EventUpdateView,
    LeadListView,
    LeadCreateView,
    LeadDeleteView,
    LeadUpdateView,
    PackageListView,
    PipelineView,
    PipelineStageCreateView,
    PipelineStageDeleteView,
    PipelineStageUpdateView,
    ServicePackageCreateView,
    ServicePackageDeleteView,
    ServicePackageUpdateView,
    TeamView,
    VendorListView,
    VendorCreateView,
    VendorDeleteView,
    VendorUpdateView,
)

app_name = "core"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("leads/", LeadListView.as_view(), name="leads"),
    path("leads/create/", LeadCreateView.as_view(), name="lead_create"),
    path("leads/<int:pk>/edit/", LeadUpdateView.as_view(), name="lead_update"),
    path("leads/<int:pk>/delete/", LeadDeleteView.as_view(), name="lead_delete"),
    path("pipeline/", PipelineView.as_view(), name="pipeline"),
    path("pipeline/create/", PipelineStageCreateView.as_view(), name="pipeline_create"),
    path("pipeline/<int:pk>/edit/", PipelineStageUpdateView.as_view(), name="pipeline_update"),
    path("pipeline/<int:pk>/delete/", PipelineStageDeleteView.as_view(), name="pipeline_delete"),
    path("clients/", ClientListView.as_view(), name="clients"),
    path("clients/create/", ClientCreateView.as_view(), name="client_create"),
    path("clients/<int:pk>/edit/", ClientUpdateView.as_view(), name="client_update"),
    path("clients/<int:pk>/delete/", ClientDeleteView.as_view(), name="client_delete"),
    path("events/", EventListView.as_view(), name="events"),
    path("events/create/", EventCreateView.as_view(), name="event_create"),
    path("events/<int:pk>/edit/", EventUpdateView.as_view(), name="event_update"),
    path("events/<int:pk>/delete/", EventDeleteView.as_view(), name="event_delete"),
    path("formats/", EventFormatListView.as_view(), name="formats"),
    path("formats/create/", EventFormatCreateView.as_view(), name="format_create"),
    path("formats/<int:pk>/edit/", EventFormatUpdateView.as_view(), name="format_update"),
    path("formats/<int:pk>/delete/", EventFormatDeleteView.as_view(), name="format_delete"),
    path("vendors/", VendorListView.as_view(), name="vendors"),
    path("vendors/create/", VendorCreateView.as_view(), name="vendor_create"),
    path("vendors/<int:pk>/edit/", VendorUpdateView.as_view(), name="vendor_update"),
    path("vendors/<int:pk>/delete/", VendorDeleteView.as_view(), name="vendor_delete"),
    path("packages/", PackageListView.as_view(), name="packages"),
    path("packages/create/", ServicePackageCreateView.as_view(), name="package_create"),
    path("packages/<int:pk>/edit/", ServicePackageUpdateView.as_view(), name="package_update"),
    path("packages/<int:pk>/delete/", ServicePackageDeleteView.as_view(), name="package_delete"),
    path("calendar/", CalendarView.as_view(), name="calendar"),
    path("analytics/", AnalyticsView.as_view(), name="analytics"),
    path("team/", TeamView.as_view(), name="team"),
]
